[package]
name = "ttfb-lib-msrv-check"
version = "0.1.0"
edition = "2024"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttfb = { path = "../" }
